<#
.SYNOPSIS
  install_submit_watcher.ps1 — Windows auto-start for the local submit watcher
  (feat/dual-machine-watcher). The Windows parity of
  scripts/install_submit_watcher.sh (which uses launchd on macOS).

.DESCRIPTION
  Registers a Scheduled Task that runs `jobpipe-submit --watch --poll 15` at
  log on and keeps it alive, mirroring the Mac LaunchAgent.

  WHY "at log on" (not "at startup"): the watcher opens a *visible* Chrome
  window to fill forms, which needs the interactive desktop session — exactly
  the reason the Mac uses a LaunchAgent (per-user GUI session) rather than a
  LaunchDaemon. A task that ran in Session 0 at boot would have no display.

  Task Scheduler can't set per-action environment variables, so this generates a
  tiny wrapper .cmd (in %LOCALAPPDATA%\jobpipe) that sets the env
  (JOBPIPE_BROWSER_CHANNEL=chrome, JOBPIPE_WATCHER_ID=desktop) and then runs the
  venv's jobpipe-submit.exe, redirecting output to a log file. The task runs that
  wrapper.

  Idempotent: an existing task with the same name is unregistered first, then
  re-registered. Re-run any time to update.

.PARAMETER Venv
  Path to the repo's virtualenv (the dir that contains Scripts\jobpipe-submit.exe).
  Defaults to .venv then venv under the repo root.

.PARAMETER WatcherId
  This machine's coordination id. Defaults to 'desktop'. The singleton
  watcher_config.active_watcher_id must equal this for this PC to claim jobs.

.PARAMETER Channel
  'chrome' (default, drives real Google Chrome) or 'chromium' (bundled).

.PARAMETER Poll
  Poll interval in seconds for the --poll fallback (default 15).

.PARAMETER WhatIf
  Show what would be registered without changing anything
  (Register-ScheduledTask honours -WhatIf).

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts\install_submit_watcher.ps1

.EXAMPLE
  .\scripts\install_submit_watcher.ps1 -WatcherId desktop -Channel chrome -WhatIf
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
  [string]$Venv = "",
  [string]$WatcherId = "desktop",
  [ValidateSet("chrome", "chromium")]
  [string]$Channel = "chrome",
  [int]$Poll = 15
)

$ErrorActionPreference = "Stop"

$TaskName = "io.thak.jobpipe.submit-watch"
# Repo root = parent of this script's directory.
$RepoDir = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path

# ── Locate the venv's jobpipe-submit.exe ──────────────────────────────────────
function Find-SubmitExe([string]$venvDir) {
  if ($venvDir) {
    $exe = Join-Path $venvDir "Scripts\jobpipe-submit.exe"
    if (Test-Path $exe) { return $exe }
    throw "jobpipe-submit.exe not found under -Venv '$venvDir'."
  }
  foreach ($candidate in @(".venv", "venv")) {
    $exe = Join-Path $RepoDir "$candidate\Scripts\jobpipe-submit.exe"
    if (Test-Path $exe) { return $exe }
  }
  throw "Could not find jobpipe-submit.exe in .venv or venv under $RepoDir. " +
        "Create the venv and run 'pip install -e .', or pass -Venv PATH."
}

$SubmitExe = Find-SubmitExe $Venv

# ── Wrapper .cmd: sets env, runs the watcher, logs to a file ───────────────────
# Task Scheduler env is limited, so the wrapper is where env + logging live.
$AppDataDir = Join-Path $env:LOCALAPPDATA "jobpipe"
New-Item -ItemType Directory -Force -Path $AppDataDir | Out-Null
$LogPath   = Join-Path $AppDataDir "submit-watch.log"
$Wrapper   = Join-Path $AppDataDir "run-submit-watch.cmd"

$channelLine = if ($Channel -eq "chrome") {
  "set ""JOBPIPE_BROWSER_CHANNEL=chrome"""
} else {
  "rem bundled Chromium (no JOBPIPE_BROWSER_CHANNEL)"
}

# >> appends so a restart keeps history; the task's RestartCount caps churn.
$wrapperBody = @"
@echo off
rem Auto-generated by scripts\install_submit_watcher.ps1 — do not edit by hand.
rem Sets env Task Scheduler can't, then runs the submit watcher with logging.
cd /d "$RepoDir"
$channelLine
set "JOBPIPE_WATCHER_ID=$WatcherId"
echo [%DATE% %TIME%] starting jobpipe-submit --watch --poll $Poll (id=$WatcherId)>> "$LogPath"
"$SubmitExe" --watch --poll $Poll >> "$LogPath" 2>&1
"@
Set-Content -Path $Wrapper -Value $wrapperBody -Encoding ASCII

Write-Host "Repo:      $RepoDir"
Write-Host "Submit:    $SubmitExe"
Write-Host "WatcherId: $WatcherId"
Write-Host "Channel:   $Channel"
Write-Host "Wrapper:   $Wrapper"
Write-Host "Log:       $LogPath"
Write-Host ""

# ── Build the scheduled task ───────────────────────────────────────────────────
$action  = New-ScheduledTaskAction -Execute "cmd.exe" -Argument "/c `"$Wrapper`"" `
                                    -WorkingDirectory $RepoDir
# At log on of THIS user (interactive desktop needed for a visible Chrome window).
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
# Keep running indefinitely; restart every minute on failure (mirrors launchd
# KeepAlive + ThrottleInterval). ExecutionTimeLimit 0 = no time limit.
$settings = New-ScheduledTaskSettingsSet `
  -AllowStartIfOnBatteries `
  -DontStopIfGoingOnBatteries `
  -RestartInterval (New-TimeSpan -Minutes 1) `
  -RestartCount 9999 `
  -ExecutionTimeLimit (New-TimeSpan -Seconds 0) `
  -StartWhenAvailable
# Run only when this user is logged on (interactive), so Chrome can show.
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive

# Idempotent: remove any existing task with this name first.
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
  Write-Host "Existing task found — unregistering first."
  if ($PSCmdlet.ShouldProcess($TaskName, "Unregister existing scheduled task")) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
  }
}

Register-ScheduledTask -TaskName $TaskName `
  -Action $action -Trigger $trigger -Settings $settings -Principal $principal `
  -Description "jobpipe local submit watcher (visible-browser pre-fill on dashboard click)." `
  | Out-Null

if ($WhatIfPreference) {
  Write-Host "`n-WhatIf: nothing was registered." -ForegroundColor Yellow
  return
}

# ── Status (mirror the .sh installer's 'is it running?' output) ────────────────
Write-Host ""
Write-Host "Status:"
$task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($task) {
  $info = Get-ScheduledTaskInfo -TaskName $TaskName
  Write-Host ("  State:        {0}" -f $task.State)
  Write-Host ("  LastRunTime:  {0}" -f $info.LastRunTime)
  Write-Host ("  LastResult:   {0}" -f $info.LastTaskResult)
  Write-Host "✓ Watcher task registered. It starts at log on and restarts on failure." -ForegroundColor Green
  Write-Host ""
  Write-Host "Start it now without logging out:  Start-ScheduledTask -TaskName $TaskName"
  Write-Host "Tail the log:                       Get-Content -Wait '$LogPath'"
  Write-Host "Then click 'Pre-fill Form' on the dashboard; a Chrome window should open."
  Write-Host ""
  Write-Host "Make this PC the active claimer:     jobpipe-submit --set-active $WatcherId"
} else {
  Write-Host "✗ Task not found after registration — check permissions." -ForegroundColor Red
  exit 1
}
